message(STATUS "Platform: ${PLATFORM}")
message(STATUS "System: ${CMAKE_SYSTEM_NAME}")
message(STATUS "System processor: ${CMAKE_SYSTEM_PROCESSOR}")
message(STATUS "Compiler ID: ${CMAKE_CXX_COMPILER_ID}")


if (WIN32)
  add_definitions(-DPLATFORM_WINDOWS)
  message(STATUS "Windows detected")
  set(PLATFORM_WINDOWS TRUE)
  if (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64")
    message(STATUS "x86_64 architecture detected")
  elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64")
    message(STATUS "ARM64 architecture detected")
  elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64")
    message(STATUS "AMD64 architecture detected")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "x86")
    message(STATUS "x86 architecture detected")
  else()
    message(FATAL_ERROR "Unsupported processor architecture: ${CMAKE_SYSTEM_PROCESSOR}")
  endif()
elseif (CMAKE_SYSTEM_NAME MATCHES "Linux")
  add_definitions(-DPLATFORM_LINUX)
  message(STATUS "Linux detected")
elseif(UNIX)
  # solaris, freebsd, etc. won't probably work with this networking stack as 
  # easily
  message(SEND_ERROR "I mean, it's Unix, but what kind of Unix, it might work, but it probably wont?")
else()
  message(FATAL_ERROR "Unsupported platform")
endif()
